# Generated by Django 6.1 on 2026-08-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('no_middle_name', False), ('middle_name', ''), _connector='OR'), name='profile_no_middle_name_consistent'),
        ),
    ]
