[project]
name = "promocode-service"
version = "0.1.0"
description = "Платформа регистрации промокодов и проведения розыгрышей"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "celery[redis]>=5.6.2",
    "django>=6.1",
    "django-unfold>=0.104.0",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
    "python-dotenv>=1.2.2",
    "drf-spectacular[sidecar]>=0.30.0",
    "gunicorn>=23.0.0",
    "openpyxl>=3.1.5",
    "psycopg2>=2.9.12",
    "whitenoise>=6.9.0",
]
