# Generated by Django 6.1 on 2026-08-11 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'promo code',
                'verbose_name_plural': 'promo codes',
                'indexes': [models.Index(fields=['registered_at'], name='promo_promo_registe_fbff05_idx'), models.Index(fields=['registered_by'], name='promo_promo_registe_3091e1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9]{8}$')), name='promo_code_format_valid')],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_code', models.CharField(max_length=64)),
                ('normalized_code', models.CharField(blank=True, max_length=8)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], max_length=16)),
                ('reason', models.CharField(choices=[('success', 'Success'), ('invalid_format', 'Invalid format'), ('not_found', 'Not found'), ('already_registered', 'Already registered'), ('profile_incomplete', 'Profile incomplete'), ('rate_limited', 'Rate limited')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'promo code attempt',
                'verbose_name_plural': 'promo code attempts',
                'indexes': [models.Index(fields=['user', 'created_at'], name='promo_promo_user_id_c26ed7_idx'), models.Index(fields=['normalized_code'], name='promo_promo_normali_21bd59_idx'), models.Index(fields=['result', 'created_at'], name='promo_promo_result_d510a4_idx')],
            },
        ),
    ]
