# Generated by Django 6.1 on 2026-08-11 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('registered_at__isnull', True), ('registered_by__isnull', True)), models.Q(('registered_at__isnull', False), ('registered_by__isnull', False)), _connector='OR'), name='promo_code_registration_consistent'),
        ),
    ]
