# Generated by Django 6.1 on 2026-08-12 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_promocode_promo_code_registration_consistent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_count', models.PositiveIntegerField()),
                ('generated_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='queued', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('lock_key', models.CharField(default='promo_codes', editable=False, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'promo code generation',
                'verbose_name_plural': 'promo code generations',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('lock_key',), name='unique_active_promo_code_generation')],
            },
        ),
    ]
