# Generated by Django 6.1 on 2026-08-14 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_promocodegeneration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='promo_imports/source/%Y/%m/%d')),
                ('original_filename', models.CharField(max_length=255)),
                ('error_file', models.FileField(blank=True, upload_to='promo_imports/errors/%Y/%m/%d')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='queued', max_length=16)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'promo code import',
                'verbose_name_plural': 'promo code imports',
                'ordering': ('-created_at',),
            },
        ),
    ]
