# Generated by Django 6.1 on 2026-08-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_promocodeimport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocodeattempt',
            name='ip_address',
        ),
    ]
