# Generated by Django 6.1 on 2026-08-14 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_remove_attempt_ip_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'промокод', 'verbose_name_plural': 'промокоды'},
        ),
        migrations.AlterModelOptions(
            name='promocodeattempt',
            options={'verbose_name': 'попытка ввода промокода', 'verbose_name_plural': 'попытки ввода промокодов'},
        ),
        migrations.AlterModelOptions(
            name='promocodegeneration',
            options={'ordering': ('-created_at',), 'verbose_name': 'генерация промокодов', 'verbose_name_plural': 'генерации промокодов'},
        ),
        migrations.AlterModelOptions(
            name='promocodeimport',
            options={'ordering': ('-created_at',), 'verbose_name': 'импорт промокодов', 'verbose_name_plural': 'импорты промокодов'},
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=8, unique=True, verbose_name='промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='зарегистрировал'),
        ),
        migrations.AlterField(
            model_name='promocodeattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата попытки'),
        ),
        migrations.AlterField(
            model_name='promocodeattempt',
            name='normalized_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='нормализованный код'),
        ),
        migrations.AlterField(
            model_name='promocodeattempt',
            name='raw_code',
            field=models.CharField(max_length=64, verbose_name='введённое значение'),
        ),
        migrations.AlterField(
            model_name='promocodeattempt',
            name='reason',
            field=models.CharField(choices=[('success', 'Успешная регистрация'), ('invalid_format', 'Неверный формат'), ('not_found', 'Код не найден'), ('already_registered', 'Код уже зарегистрирован'), ('profile_incomplete', 'Профиль не заполнен'), ('rate_limited', 'Превышен лимит попыток')], max_length=32, verbose_name='причина'),
        ),
        migrations.AlterField(
            model_name='promocodeattempt',
            name='result',
            field=models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка'), ('blocked', 'Заблокировано')], max_length=16, verbose_name='результат'),
        ),
        migrations.AlterField(
            model_name='promocodeattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_attempts', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='promocodegeneration',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID задачи Celery'),
        ),
        migrations.AlterField(
            model_name='promocodegeneration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создана'),
        ),
        migrations.AlterField(
            model_name='promocodegeneration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_generations', to=settings.AUTH_USER_MODEL, verbose_name='запустил'),
        ),
        migrations.AlterField(
            model_name='promocodegeneration',
            name='error',
            field=models.TextField(blank=True, verbose_name='ошибка'),
        ),
        migrations.AlterField(
            model_name='promocodegeneration',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='завершена'),
        ),
        migrations.AlterField(
            model_name='promocodegeneration',
            name='generated_count',
            field=models.PositiveIntegerField(default=0, verbose_name='сгенерировано кодов'),
        ),
        migrations.AlterField(
            model_name='promocodegeneration',
            name='requested_count',
            field=models.PositiveIntegerField(verbose_name='запрошено кодов'),
        ),
        migrations.AlterField(
            model_name='promocodegeneration',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начата'),
        ),
        migrations.AlterField(
            model_name='promocodegeneration',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='queued', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID задачи Celery'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_imports', to=settings.AUTH_USER_MODEL, verbose_name='загрузил'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='error',
            field=models.TextField(blank=True, verbose_name='ошибка'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='error_file',
            field=models.FileField(blank=True, upload_to='promo_imports/errors/%Y/%m/%d', verbose_name='файл с пропущенными строками'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='завершён'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='imported_count',
            field=models.PositiveIntegerField(default=0, verbose_name='импортировано кодов'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='original_filename',
            field=models.CharField(max_length=255, verbose_name='имя исходного файла'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='processed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='обработано строк'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='пропущено строк'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='source_file',
            field=models.FileField(upload_to='promo_imports/source/%Y/%m/%d', verbose_name='исходный файл'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начат'),
        ),
        migrations.AlterField(
            model_name='promocodeimport',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='queued', max_length=16, verbose_name='статус'),
        ),
    ]
