# Generated by Django 6.1 on 2026-08-14 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('promo_generation_queued', 'Генерация кодов поставлена в очередь'), ('promo_generation_started', 'Генерация кодов началась'), ('promo_generation_completed', 'Генерация кодов завершена'), ('promo_generation_failed', 'Генерация кодов завершилась ошибкой'), ('promo_import_queued', 'Импорт кодов поставлен в очередь'), ('promo_import_started', 'Импорт кодов начался'), ('promo_import_completed', 'Импорт кодов завершён'), ('promo_import_failed', 'Импорт кодов завершился ошибкой'), ('draw_queued', 'Розыгрыш поставлен в очередь'), ('draw_completed', 'Розыгрыш завершён'), ('draw_failed', 'Розыгрыш завершился ошибкой'), ('draw_report_queued', 'Отчёт поставлен в очередь'), ('draw_report_started', 'Формирование отчёта началось'), ('draw_report_completed', 'Формирование отчёта завершено'), ('draw_report_failed', 'Формирование отчёта завершилось ошибкой'), ('audit_cleanup_completed', 'Очистка аудита завершена')], max_length=64)),
                ('target_model', models.CharField(blank=True, max_length=128)),
                ('target_object_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_auditl_event_t_f36ba9_idx'), models.Index(fields=['actor', 'created_at'], name='core_auditl_actor_i_41600a_idx'), models.Index(fields=['target_model', 'target_object_id'], name='core_auditl_target__d419bd_idx')],
            },
        ),
    ]
