# Generated by Django 6.1 on 2026-08-14 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'событие аудита', 'verbose_name_plural': 'журнал аудита'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='инициатор'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата события'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('promo_generation_queued', 'Генерация кодов поставлена в очередь'), ('promo_generation_started', 'Генерация кодов началась'), ('promo_generation_completed', 'Генерация кодов завершена'), ('promo_generation_failed', 'Генерация кодов завершилась ошибкой'), ('promo_import_queued', 'Импорт кодов поставлен в очередь'), ('promo_import_started', 'Импорт кодов начался'), ('promo_import_completed', 'Импорт кодов завершён'), ('promo_import_failed', 'Импорт кодов завершился ошибкой'), ('draw_queued', 'Розыгрыш поставлен в очередь'), ('draw_completed', 'Розыгрыш завершён'), ('draw_failed', 'Розыгрыш завершился ошибкой'), ('draw_report_queued', 'Отчёт поставлен в очередь'), ('draw_report_started', 'Формирование отчёта началось'), ('draw_report_completed', 'Формирование отчёта завершено'), ('draw_report_failed', 'Формирование отчёта завершилось ошибкой'), ('audit_cleanup_completed', 'Очистка аудита завершена')], max_length=64, verbose_name='событие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_model',
            field=models.CharField(blank=True, max_length=128, verbose_name='модель объекта'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID объекта'),
        ),
    ]
