# Generated by Django 6.1 on 2026-08-11 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField()),
                ('prize', models.CharField(choices=[('ozon_1500', 'Ozon 1500'), ('ozon_3000', 'Ozon 3000'), ('ozon_5000', 'Ozon 5000')], max_length=32)),
                ('won_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('promo_code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='promo.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'winner',
                'verbose_name_plural': 'winners',
                'indexes': [models.Index(fields=['draw_date'], name='draws_winne_draw_da_6214c4_idx')],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_winner_user'), models.UniqueConstraint(fields=('draw_date', 'prize'), name='unique_prize_per_draw_date')],
            },
        ),
    ]
