# Generated by Django 6.1 on 2026-08-11 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Min


def move_winners_to_draws(apps, schema_editor):
    Draw = apps.get_model('draws', 'Draw')
    Winner = apps.get_model('draws', 'Winner')

    invalid_prizes = Winner.objects.exclude(
        prize__in=('ozon_3000', 'airpods'),
    )
    if invalid_prizes.exists():
        raise RuntimeError(
            'Existing winners contain prizes that are no longer supported.'
        )

    draw_dates = (
        Winner.objects.order_by()
        .values_list('draw_date', flat=True)
        .distinct()
    )
    for draw_date in draw_dates.iterator():
        won_at = Winner.objects.filter(draw_date=draw_date).aggregate(
            won_at=Min('won_at'),
        )['won_at']
        draw = Draw.objects.create(
            draw_date=draw_date,
            status='completed',
            started_at=won_at,
            completed_at=won_at,
        )
        Winner.objects.filter(draw_date=draw_date).update(draw=draw)


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0001_initial'),
        ('promo', '0002_promocode_promo_code_registration_consistent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('trigger', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'draw',
                'verbose_name_plural': 'draws',
                'ordering': ['-draw_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='winner',
            options={'ordering': ['-won_at'], 'verbose_name': 'winner', 'verbose_name_plural': 'winners'},
        ),
        migrations.RemoveConstraint(
            model_name='winner',
            name='unique_prize_per_draw_date',
        ),
        migrations.RemoveIndex(
            model_name='winner',
            name='draws_winne_draw_da_6214c4_idx',
        ),
        migrations.AlterField(
            model_name='winner',
            name='prize',
            field=models.CharField(choices=[('ozon_3000', 'Ozon 3000'), ('airpods', 'AirPods')], max_length=32),
        ),
        migrations.AddField(
            model_name='winner',
            name='draw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winners', to='draws.draw'),
        ),
        migrations.RunPython(
            move_winners_to_draws,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='winner',
            constraint=models.UniqueConstraint(fields=('draw', 'prize'), name='unique_prize_per_draw'),
        ),
        migrations.RemoveField(
            model_name='winner',
            name='draw_date',
        ),
        migrations.AlterField(
            model_name='winner',
            name='draw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winners', to='draws.draw'),
        ),
    ]
