# Generated by Django 6.1 on 2026-08-12 06:26

from django.conf import settings
from django.db import migrations, models


def normalize_choice(value):
    return ''.join(character for character in value.lower() if character.isalnum())


def normalize_draw_values(apps, schema_editor):
    Draw = apps.get_model('draws', 'Draw')
    Winner = apps.get_model('draws', 'Winner')
    status_values = {
        'pending': 'pending',
        'running': 'running',
        'completed': 'completed',
        'complete': 'completed',
        'success': 'completed',
        'succes': 'completed',
        'failed': 'failed',
        'error': 'failed',
    }
    trigger_values = {
        'automatic': 'automatic',
        'auto': 'automatic',
        'celery': 'automatic',
        'celry': 'automatic',
        'manual': 'manual',
    }
    prize_values = {
        'ozon3000': 'ozon_3000',
        'airpods': 'airpods',
    }

    for draw in Draw.objects.all().iterator():
        status = status_values.get(normalize_choice(draw.status))
        trigger = trigger_values.get(normalize_choice(draw.trigger))
        if status is None or trigger is None:
            raise RuntimeError(
                f'Draw {draw.pk} has unsupported status or trigger.'
            )
        Draw.objects.filter(pk=draw.pk).update(
            status=status,
            trigger=trigger,
        )

    for winner in Winner.objects.all().iterator():
        prize = prize_values.get(normalize_choice(winner.prize))
        if prize is None:
            raise RuntimeError(
                f'Winner {winner.pk} has unsupported prize.'
            )
        Winner.objects.filter(pk=winner.pk).update(prize=prize)


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0002_draw_alter_winner_options_and_more'),
        ('promo', '0003_promocodegeneration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            normalize_draw_values,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='draw',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'running', 'completed', 'failed'))), name='draw_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='draw',
            constraint=models.CheckConstraint(condition=models.Q(('trigger__in', ('automatic', 'manual'))), name='draw_trigger_valid'),
        ),
        migrations.AddConstraint(
            model_name='winner',
            constraint=models.CheckConstraint(condition=models.Q(('prize__in', ('ozon_3000', 'airpods'))), name='winner_prize_valid'),
        ),
    ]
