# Generated by Django 6.1 on 2026-08-13 03:25

from datetime import datetime, time, timedelta
from zoneinfo import ZoneInfo

from django.conf import settings
from django.db import migrations, models


def populate_draw_periods(apps, schema_editor):
    Draw = apps.get_model('draws', 'Draw')
    campaign_timezone = ZoneInfo(settings.TIME_ZONE)
    previous_end = None

    draws = Draw.objects.filter(status='completed').order_by(
        'draw_date', 'completed_at', 'pk'
    )
    for draw in draws.iterator():
        calendar_start = datetime.combine(
            draw.draw_date, time.min, campaign_timezone
        )
        starts_at = previous_end or calendar_start
        calendar_end = calendar_start + timedelta(days=1)
        ends_at = (
            draw.completed_at
            if draw.trigger == 'manual' and draw.completed_at
            else calendar_end
        )
        if ends_at <= starts_at:
            starts_at = calendar_start
            ends_at = max(calendar_end, draw.completed_at or calendar_end)
        Draw.objects.filter(pk=draw.pk).update(
            period_started_at=starts_at,
            period_ended_at=ends_at,
        )
        previous_end = ends_at


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0003_draw_draw_status_valid_draw_draw_trigger_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='period_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draw',
            name='period_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_draw_periods,
            migrations.RunPython.noop,
        ),
    ]
