# Generated by Django 6.1 on 2026-08-14 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0005_drawreport'),
        ('promo', '0006_translate_admin_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draw',
            options={'ordering': ['-draw_date'], 'verbose_name': 'розыгрыш', 'verbose_name_plural': 'розыгрыши'},
        ),
        migrations.AlterModelOptions(
            name='drawreport',
            options={'ordering': ('-created_at',), 'verbose_name': 'отчёт по розыгрышам', 'verbose_name_plural': 'отчёты по розыгрышам'},
        ),
        migrations.AlterModelOptions(
            name='winner',
            options={'ordering': ['-won_at'], 'verbose_name': 'победитель', 'verbose_name_plural': 'победители'},
        ),
        migrations.AlterField(
            model_name='draw',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='завершён'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='draw_date',
            field=models.DateField(unique=True, verbose_name='дата розыгрыша'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='period_ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='конец периода кодов'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='period_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начало периода кодов'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начат'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает запуска'), ('running', 'Выполняется'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='trigger',
            field=models.CharField(choices=[('automatic', 'Автоматический'), ('manual', 'Ручной')], default='automatic', max_length=16, verbose_name='способ запуска'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлён'),
        ),
        migrations.AlterField(
            model_name='drawreport',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID задачи Celery'),
        ),
        migrations.AlterField(
            model_name='drawreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='drawreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw_reports', to=settings.AUTH_USER_MODEL, verbose_name='сформировал'),
        ),
        migrations.AlterField(
            model_name='drawreport',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='drawreport',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='drawreport',
            name='error',
            field=models.TextField(blank=True, verbose_name='ошибка'),
        ),
        migrations.AlterField(
            model_name='drawreport',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='завершён'),
        ),
        migrations.AlterField(
            model_name='drawreport',
            name='report_file',
            field=models.FileField(blank=True, upload_to='draw_reports/%Y/%m/%d', verbose_name='файл отчёта'),
        ),
        migrations.AlterField(
            model_name='drawreport',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начат'),
        ),
        migrations.AlterField(
            model_name='drawreport',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='queued', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='draw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winners', to='draws.draw', verbose_name='розыгрыш'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='письмо отправлено'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='prize',
            field=models.CharField(choices=[('ozon_3000', 'Сертификат Ozon на 3 000 рублей'), ('airpods', 'Наушники AirPods')], max_length=32, verbose_name='приз'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='promo_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='promo.promocode', verbose_name='промокод'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wins', to=settings.AUTH_USER_MODEL, verbose_name='победитель'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='won_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата победы'),
        ),
    ]
