# Generated by Django 6.1 on 2026-08-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0006_translate_admin_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draw',
            options={'ordering': ['-draw_date'], 'permissions': [('run_draw', 'Может проводить ручной розыгрыш')], 'verbose_name': 'розыгрыш', 'verbose_name_plural': 'розыгрыши'},
        ),
    ]
